#%YAML:1.0
names:
   - robocup_table
   - robocup_shelf
robocup_table:
   type: Table
   width:  0.8
   height: 0.717
   depth: 0.8    
   z_rot: 0.0
   transform: #!!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 1., 0., 0., 0.9, 
      0., 1., 0., 0.55, 
      0., 0., 1., 0.365,
      0., 0., 0., 1. ]
robocup_shelf:
   type: Shelf
   width: 0.99
   height: 1.5
   depth: 0.35
   z_rot: 4.71238898038 # pi * 1.5
   transform: #!!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 0., 1., 0., 0., 
      -1., 0., 0., -0.4, 
      0., 0., 1., 0.8,
      0., 0., 0., 1. ]